# Generated by Django 5.2.14 on 2026-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
