# Generated by Django 5.2.14 on 2026-06-02 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_date_alter_invoice_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='banana_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='VehicleTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_phone', models.CharField(max_length=20)),
                ('total_gross_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_net_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pieces', models.IntegerField()),
                ('bananas', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_transports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
