# Generated by Django 5.2.14 on 2026-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_weightentry_banana_type_weightentry_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, default='1234', max_length=4),
        ),
    ]
